#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

CURRENT_COMMIT_MESSAGE=$(cat $1)
COMMIT_MESSAGE_TO_SKIP_REGEXP="^chore\(release\): [0-9]+\.[0-9]+\.[0-9]+$"

if ! echo "$CURRENT_COMMIT_MESSAGE" | grep -Eq "$COMMIT_MESSAGE_TO_SKIP_REGEXP"; then
  npx --no-install jira-prepare-commit-msg $1
fi
